#!/bin/sh

cd ~

rm ~/.emacs.d/init.el
rm .bashrc
rm .bash_profile
rm .gitconfig
rm .git-completion.bash
rm .tmux.conf
rm .ackrc

ln -s   ~/emacs_libs/home-config-files/bashrc   .bashrc
ln -s   ~/emacs_libs/home-config-files/bash_profile   .bash_profile

ln -s ~/emacs_libs/home-config-files/init.el   ~/.emacs.d/init.el
ln -s ~/emacs_libs/home-config-files/git-completion.bash   ~/.git-completion.bash
ln -s ~/emacs_libs/home-config-files/gitconfig   ~/.gitconfig
ln -s ~/emacs_libs/home-config-files/tmux.conf   ~/.tmux.conf
ln -s ~/emacs_libs/home-config-files/ackrc   ~/.ackrc 

ln -s ~/emacs_libs/bin ~/bin


source ~/.bashrc
